-- Clase 14 - Triggers (parte A)

    /*
        Creación de un TRIGGER que nos permita crear una bitácora.
    */
    -- Creación de la tabla para almacenar la bitácora
CREATE TABLE BITACORAS(
    PK_COD_BITACORA NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(2000),
    FECHA_HORA TIMESTAMP,
    USUARIO VARCHAR2(100),
    OPERTACION VARCHAR2(50)
);

    -- Creación de la secuencia que permita gestionar el valor autoincremental de la llave primaria
CREATE SEQUENCE SQ_BITACORAS
START WITH 1
INCREMENT BY 1;

    -- Creación del Trigger
CREATE OR REPLACE TRIGGER TG_CATEGORIAS
AFTER INSERT ON CATEGORIES
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA VALUES (SQ_BITACORA.NEXTVAL, 'SE REALIZO UN INSERT EN LA TABLA CATEGORIAS Y EL DATO NUEVO ES: '||:NEW.CATEGORY_ID||' Y EL NOMBRE DE LA CATEGORIA ES: '||:NEW.CATEGORY_NAME, SYSTIMESTAMP, USER, 'OPERACION INSERT');
END;

    -- Realizando la inserción
BEGIN
    INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES ('BICILCETAS PLAYERAS');
    COMMIT;
END;

    -- Utilizando transacciones anónimas
CREATE OR REPLACE TRIGGER TG_CATEGORIAS
AFTER INSERT ON CATEGORIES
FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO BITACORA VALUES (SQ_BITACORA.NEXTVAL, 'SE REALIZO UN INSERT EN LA TABLA CATEGORIAS Y EL DATO NUEVO ES: '||:NEW.CATEGORY_ID||' Y EL NOMBRE DE LA CATEGORIA ES: '||:NEW.CATEGORY_NAME, SYSTIMESTAMP, USER, 'OPERACION INSERT');
    COMMIT;
END;

BEGIN
    INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES ('BICILCETAS DE PISTAS');
    COMMIT;
END;

    -- Capturando excepciones en un TRIGGER
CREATE OR REPLACE TRIGGER TG_CATEGORIAS
AFTER INSERT ON CATEGORIES
FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO BITACORA VALUES (3, 'SE REALIZO UN INSERT EN LA TABLA CATEGORIAS Y EL DATO NUEVO ES: '||:NEW.CATEGORY_ID||' Y EL NOMBRE DE LA CATEGORIA ES: '||:NEW.CATEGORY_NAME, SYSTIMESTAMP, USER, 'OPERACION INSERT');
    COMMIT;

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
END;

BEGIN
    INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES ('BICILCETAS DE PISTAS');
    COMMIT;
END;