-- Clase 11 - Gestión de Transacciones
    
    -- Gestion de transacciones vinculada a la gestión de excepciones
DECLARE

BEGIN
    INSERT INTO BRANDS VALUES (13, 'MOUNTAIN BICI');
    COMMIT;
    INSERT INTO BRANDS VALUES (14, 'BICI SHOP');
    COMMIT;
    INSERT INTO BRANDS VALUES (12, 'ELECTRO BICI');
    COMMIT;

    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('ERROR DE LLAVE PRIMARIA');
        ROLLBACK;
END;

    -- Ejecutando o salvando estados en la base de datos
DECLARE

BEGIN
    UPDATE BRANDS SET BRAND_NAME=BRAND_NAME||'2019' WHERE BRAND_ID=1;
    UPDATE BRANDS SET BRAND_NAME=BRAND_NAME||'2019' WHERE BRAND_ID=2;
    COMMIT;
    SAVEPOINT DATOS_MODIFICADOS;

    UPDATE BRANDS SET BRAND_ID=1, BRAND_NAME=BRAND_NAME||'2021' WHERE BRAND_ID=14;
    COMMIT;
    SAVEPOINT DATOS_MODIFICADOS;

    UPDATE BRANDS SET BRAND_NAME=BRAND_NAME||'2020' WHERE BRAND_ID=3 OR BRAND_ID=4;
    COMMIT;
    SAVEPOINT DATOS_MODIFICADOS;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            DBMS_OUTPUT.PUT_LINE('ERROR DE LLAVE PRIMARIA');
            ROLLBACK TO SAVEPOINT DATOS_MODIFICADOS;
END;