-- Clase 5 - Ciclos

	-- Ciclo de repetición LOOP sencillo.
DECLARE
	ITERACION NUMBER(3):=0;
	FECHA DATE;

BEGIN
	LOOP
		FECHA:=sysdate+ITERACION;
		EXIT WHEN ITERACION>3;
		DBMS_OUTPUT.PUT_LINE('ciclo'||ITERACION);
		DBMS_OUTPUT.PUT_LINE(FECHA);
		ITERACION:=ITERACION+1;
	END LOOP;
END;

    -- Ciclo de repetición WHILE sencillo.
DECLARE
	ITERACION NUMBER(3):=0;
	FECHA DATE;

BEGIN
	WHILE
		FECHA:=sysdate+ITERACION;
		EXIT WHEN ITERACION>3;
		DBMS_OUTPUT.PUT_LINE('ciclo'||ITERACION);
		DBMS_OUTPUT.PUT_LINE(FECHA);
		ITERACION:=ITERACION+1;
	END LOOP;
END;

    -- Ciclo de repetición FOR sencillo.
DECLARE
	ITERACION NUMBER(3):=0;
	FECHA DATE;

BEGIN
	FOR ITERACION IN O..5 LOOP
		FECHA:=sysdate+ITERACION;
		EXIT WHEN ITERACION>3;
		DBMS_OUTPUT.PUT_LINE('ciclo'||ITERACION);
		DBMS_OUTPUT.PUT_LINE(FECHA);
		ITERACION:=ITERACION+1;
	END LOOP;
END;
