-- Clase 7 - SELECT INTO (parte A)

	-- La instrucción SELECT INTO permite embeber el resultado de una consulta dentro de una variable.

DECLARE 
	NOMBRE PRODUCTS.PRODUCT_NAME%TYPE;
	ITERACION NUMBER(10):=1;
	CANTIDAD_PRODUCTOS NUMBER(10);

BEGIN
	SELECT COUNT(PRODUCT_NAME) INTO CANTIDAD_PRODUCTOS FROM PRODUCTS;
	-- El resultado del conteo de elementos de la tabla productos, será asignado a la variable CANTIDAD_PRODUCTOS.

	LOOP
		EXIT WHEN ITERACION>CANTIDAD_PRODUCTOS;
		SELECT PRODUCT_NAME INTO NOMBRE FROM PRODUCTS WHERE PRODUCT_ID = ITERACION;
		DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL PRODUCTO CON ID '||ITERACION||' ES: '||NOMBRE);
		ITERACION:=ITERACION+1;
	END LOOP;

END;